import AuthProvider from './context/AuthProvider';
import './globals.css';

export const metadata = {
  title: 'test',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='min-h-screen'>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}